### PR TITLE
Support for ratings & reviews in Storefront App

### PR DESCRIPTION
**Pull request by aleksejsbaranovs10**
### Related Pull Requests
https://github.com/magento/storefront-message-broker/pull/5
https://github.com/magento/storefront-product-reviews-ce/pull/1
https://github.com/magento/commerce-data-export/pull/2

https://github.com/magento-commerce/magento2-infrastructure/pull/1376

### Fixed Issues (if relevant)

1. Fixes magento/catalog-storefront#351

### Code Review Checklist (*)

See detailed [checklist](https://github.com/magento/catalog-storefront/blob/develop/dev/docs/projectAgreements/Code-Review-checklist.md)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
  - expected results in test verified with data from fixture
- [ ] no backward incompatible changes
- [ ] Export API (et_schema.xml) and SF API schemas (proto schema) are reflected in the codebase
  - prerequisite: story branch created with all needed generated classes according to proposes schema-changes
  - DTO classes do not contain any manual changes (Magento\CatalogExportApi\*, Magento\CatalogStorefrontApi\*)
- [ ] Class usage: magento/catalog-storefront repo don't use directly classes from magento/saas-export repo and vise-verse
  - Check composer.json dependencies
- [ ] Legacy code is deleted
  - Any Data Providers present in Connector part  (Magento\CatalogStorefrontConnector, Magento\*Extractor modules)
  - And Data Providers from Export API (magento/saas-export repo) that is not relevant anymore
  - Any DTO for Export API/SF API which does not reflect current schema: et_schema, proto schema
  - Any “mapper” on Message Broker (between Export API and SF API)
    - if mapper still needed, verify fields used in mapping, remove not relevant fields

### CODE REVIEW

**Comment by RuslanKostiv1** [comment]
@magento run WebAPI Tests

**Comment by RuslanKostiv1** [comment]
@magento run Magento Health Index

**Comment by RuslanKostiv1** [comment]
@magento run WebAPI Tests

**Comment by RuslanKostiv1** [comment]
@magento run WebAPI Tests

**Comment by RuslanKostiv1** [comment]
@magento run WebAPI Tests

**Comment by aleksejsbaranovs10** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run Static Tests

**Comment by RuslanKostiv1** [comment]
```
Data set: app/code/Magento/DataExporter/Model/Query/MarkRemovedEntitiesQuery.php
Module Magento\DataExporter has undeclared dependencies: hard [Magento\Store]
/var/www/html/dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:474
/var/www/html/lib/internal/Magento/Framework/App/Utility/AggregateInvoker.php:56
/var/www/html/dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:477
```
@aleksejsbaranovs10 there are still such kind of failures, `MarkRemovedEntitiesQuery` uses table `store` that declared in `Magento\Store` module. This module must be added as dependency in `app/code/Magento/DataExporter/composer.json` file. Please add missing dependencies in other modules mentioned in error logs.

**Comment by aleksejsbaranovs10** [comment]
> ```
> Data set: app/code/Magento/DataExporter/Model/Query/MarkRemovedEntitiesQuery.php
> Module Magento\DataExporter has undeclared dependencies: hard [Magento\Store]
> /var/www/html/dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:474
> /var/www/html/lib/internal/Magento/Framework/App/Utility/AggregateInvoker.php:56
> /var/www/html/dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:477
> ```
> 
> @aleksejsbaranovs10 there are still such kind of failures, `MarkRemovedEntitiesQuery` uses table `store` that declared in `Magento\Store` module. This module must be added as dependency in `app/code/Magento/DataExporter/composer.json` file. Please add missing dependencies in other modules mentioned in error logs.

Hello @RuslanKostiv1 , that was already done in https://github.com/magento/commerce-data-export/pull/2/commits/4f6ddf2e976ac54fbcf0c5cb607fb51c1c88a777#diff-f47b0dada994014e45455a1084f2c755381f5ac4f48d0e318d3cd4ae4fe8da02 commit. Waiting for Static Tests run

**Comment by RuslanKostiv1** [comment]
@magento run  Unit Tests

**Comment by RuslanKostiv1** [comment]
@magento run Static Tests

**Comment by RuslanKostiv1** [comment]
@magento run Magento Health Index

**Comment by RuslanKostiv1** [comment]
@magento run Magento Health Index, Static Tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run Static Tests

**Comment by aleksejsbaranovs10** [comment]
@magento run Static Tests

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run all tests

**Comment by aleksejsbaranovs10** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento import pr to magento-commerce/catalog-storefront-ce

**Comment by magento-engcom-team** [comment]
@RuslanKostiv1 the pull request successfully imported.

**Pull request merged**
