### PR TITLE
345 support for url rewrites

### PR DESCRIPTION
**Pull request by owlsmage**
### Description (*)

added url_rewrites to $map
changed url => canonical_url in $map
removed code from CatalogExtractor

### Related Pull Requests

https://github.com/magento/commerce-data-export/pull/6
https://github.com/magento/commerce-data-export-ee/pull/2

### Code Review Checklist (*)

See dataied [checklist](https://github.com/magento/catalog-storefront/wiki/Code-Review-checklist)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
  - expected results in test verified with data from fixture
- [ ] no backward incompatibile changes
- [ ] Export API (et_schema.xml) and SF API schemas (proto schema) are reflected in the codebase
  - prerequisite: story branch created with all needed generated classes according to proposes schema-changes
  - DTO classes do not contain any manual changes (Magento\CatalogExportApi\*, Magento\CatalogStorefrontApi\*)
- [ ] Class usage: magento/catalog-storefront repo don't use directly classes from magento/saas-export repo and vise-verse
  - Check composer.json dependencies
- [ ] Legacy code is deleted
  - Any Data Providers present in Connector part  (Magento\CatalogStorefrontConnector, Magento\*Extractor modules)
  - And Data Providers from Export API (magento/saas-export repo) that is not relevant anymore
  - Any DTO for Export API/SF API which does not reflect current schema: et_schema, proto schema
  - Any “mapper” on Message Broker (between Export API and SF API)
    - if mapper still needed, verify fields used in mapping, remove not relevant fields

### CODE REVIEW

**Comment by owlsmage** [comment]
@magento run all tests

**Comment by owlsmage** [comment]
@magento run all tests

**Review by RuslanKostiv1 — CHANGES_REQUESTED** [review]
Please fix merge conflicts

**Comment by mslabko** [comment]
@magento run all tests

**Comment by mslabko** [comment]
@magento run all tests

**Comment by owlsmage** [comment]
@magento run WebAPI Tests

**Comment by mslabko** [comment]
@magento run WebAPI Tests

**Comment by mslabko** [comment]
@magento run all tests

**Comment by RuslanKostiv1** [comment]
@magento import pr to magento-commerce/catalog-storefront-ce

**Comment by magento-engcom-team** [comment]
@RuslanKostiv1 the pull request successfully imported.

**Pull request merged**
